// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC73yIcBZi13JUWQsdwAR_wlf8R5tDrv68',
    appId: '1:719739137482:web:c20ed6dba441bfc1957333',
    messagingSenderId: '719739137482',
    projectId: 'cortinasiot',
    authDomain: 'cortinasiot.firebaseapp.com',
    storageBucket: 'cortinasiot.appspot.com',
    measurementId: 'G-1MGGMSSZ5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcMJrmMBNNxGheQAgPvj__R9Lvh6Q9-Bw',
    appId: '1:719739137482:android:092645d820d27bcf957333',
    messagingSenderId: '719739137482',
    projectId: 'cortinasiot',
    storageBucket: 'cortinasiot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACaaH56wS8rYeB5-Qj_RNXLQZgOHuNC7E',
    appId: '1:719739137482:ios:399dc318ede3542b957333',
    messagingSenderId: '719739137482',
    projectId: 'cortinasiot',
    storageBucket: 'cortinasiot.appspot.com',
    iosBundleId: 'com.example.cortinasIot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACaaH56wS8rYeB5-Qj_RNXLQZgOHuNC7E',
    appId: '1:719739137482:ios:399dc318ede3542b957333',
    messagingSenderId: '719739137482',
    projectId: 'cortinasiot',
    storageBucket: 'cortinasiot.appspot.com',
    iosBundleId: 'com.example.cortinasIot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC73yIcBZi13JUWQsdwAR_wlf8R5tDrv68',
    appId: '1:719739137482:web:cc74c003e3a194c4957333',
    messagingSenderId: '719739137482',
    projectId: 'cortinasiot',
    authDomain: 'cortinasiot.firebaseapp.com',
    storageBucket: 'cortinasiot.appspot.com',
    measurementId: 'G-8CP1BJPHJX',
  );

}